import esbuild from "esbuild";
import process from "process";
import { builtinModules } from "module";
import path from "path";
import { fileURLToPath } from "url";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";
const dirname = path.dirname(fileURLToPath(import.meta.url));
const setImmediateShimPath = path.join(dirname, "src/shims/setimmediate.ts");
const nativePromiseShimPath = path.join(dirname, "src/shims/nativePromise.cjs");

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtinModules,
	],
	format: "cjs",
	target: "es2020",
	logLevel: "info",
	plugins: [
		{
			name: "safe-setimmediate-shim",
			setup(build) {
				build.onResolve({ filter: /^setimmediate$/ }, () => ({
					path: setImmediateShimPath,
				}));
				build.onResolve({ filter: /^lie$/ }, () => ({
					path: nativePromiseShimPath,
				}));
			},
		},
	],
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	platform: "node",
	minify: prod,
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
