import esbuild from "esbuild";
import process from "process";
import fs from "fs";
import { builtinModules } from "module";
import path from "path";
import { fileURLToPath } from "url";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";
const dirname = path.dirname(fileURLToPath(import.meta.url));
const jsZipSourceEntryPath = path.join(dirname, "node_modules/jszip/lib/index.js");
const setImmediateShimPath = path.join(dirname, "src/shims/setimmediate.ts");
const nativePromiseShimPath = path.join(dirname, "src/shims/nativePromise.cjs");
const globalsShimPath = path.join(dirname, "src/shims/globals.ts");
const browserAliases = new Map([
	["buffer", path.join(dirname, "node_modules/buffer/index.js")],
	["path", path.join(dirname, "src/shims/desktopPath.ts")],
	["process", path.join(dirname, "node_modules/process/browser.js")],
	["stream", path.join(dirname, "node_modules/stream-browserify/index.js")],
	["zlib", path.join(dirname, "src/shims/desktopZlib.ts")],
	["util", path.join(dirname, "node_modules/util/util.js")],
	["events", path.join(dirname, "node_modules/events/events.js")],
	["assert", path.join(dirname, "node_modules/assert/build/assert.js")],
	["string_decoder/", path.join(dirname, "node_modules/string_decoder/lib/string_decoder.js")],
	["fs", path.join(dirname, "src/shims/desktopFs.ts")],
	["node:fs", path.join(dirname, "src/shims/desktopFs.ts")],
	["fs/promises", path.join(dirname, "src/shims/desktopFsPromises.ts")],
	["child_process", path.join(dirname, "src/shims/desktopChildProcess.ts")],
	["os", path.join(dirname, "src/shims/desktopOs.ts")],
	["stream/promises", path.join(dirname, "src/shims/desktopStreamPromises.ts")],
]);

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	inject: [globalsShimPath],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtinModules.filter((name) => !browserAliases.has(name) && name !== "string_decoder"),
	],
	format: "cjs",
	target: "es2020",
	logLevel: "info",
	plugins: [
		{
			name: "mobile-node-compat",
			setup(build) {
				build.onResolve({ filter: /^(buffer|path|process|stream|zlib|util|events|assert|string_decoder\/|fs|node:fs|fs\/promises|child_process|os|stream\/promises)$/ }, (args) => ({
					path: browserAliases.get(args.path),
				}));
			}
		},
		{
			name: "safe-jszip-runtime",
			setup(build) {
				// JSZip's browser field redirects its source entry to a pre-bundled
				// Browserify artifact. That artifact contains legacy IE fallbacks
				// which dynamically create <script> elements, and its internal
				// dependencies can no longer be replaced by the shims below.
				build.onResolve({ filter: /^jszip$/ }, () => ({
					path: jsZipSourceEntryPath,
				}));
				build.onResolve({ filter: /^setimmediate$/ }, () => ({
					path: setImmediateShimPath,
				}));
				build.onResolve({ filter: /^lie$/ }, () => ({
					path: nativePromiseShimPath,
				}));
			},
		},
		{
			// PDF.js inspects the Node `process` global to choose its Node vs
			// browser code path. Obsidian's Electron renderer exposes `process`,
			// so shadow it with a module-scoped `undefined` at build time: this
			// forces PDF.js onto its browser DOM path (the same effect the old
			// blob loader had by prepending the line, but with a static import
			// instead of a review-flagged dynamic import()).
			name: "pdfjs-process-shim",
			setup(build) {
				build.onLoad({ filter: /pdf\.min\.mjs$/ }, (args) => ({
					contents: "const process = undefined;\n" + fs.readFileSync(args.path, "utf8"),
					loader: "js",
				}));
			},
		},
	],
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	platform: "browser",
	minify: prod,
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
