import esbuild from "esbuild";
import process from "process";
import fs from "fs";
import { builtinModules } from "module";
import path from "path";
import { fileURLToPath } from "url";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";
const dirname = path.dirname(fileURLToPath(import.meta.url));
const setImmediateShimPath = path.join(dirname, "src/shims/setimmediate.ts");
const nativePromiseShimPath = path.join(dirname, "src/shims/nativePromise.cjs");

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtinModules,
	],
	format: "cjs",
	target: "es2020",
	logLevel: "info",
	plugins: [
		{
			name: "safe-setimmediate-shim",
			setup(build) {
				build.onResolve({ filter: /^setimmediate$/ }, () => ({
					path: setImmediateShimPath,
				}));
				build.onResolve({ filter: /^lie$/ }, () => ({
					path: nativePromiseShimPath,
				}));
			},
		},
		{
			// PDF.js inspects the Node `process` global to choose its Node vs
			// browser code path. Obsidian's Electron renderer exposes `process`,
			// so shadow it with a module-scoped `undefined` at build time: this
			// forces PDF.js onto its browser DOM path (the same effect the old
			// blob loader had by prepending the line, but with a static import
			// instead of a review-flagged dynamic import()).
			name: "pdfjs-process-shim",
			setup(build) {
				build.onLoad({ filter: /pdf\.min\.mjs$/ }, (args) => ({
					contents: "const process = undefined;\n" + fs.readFileSync(args.path, "utf8"),
					loader: "js",
				}));
			},
		},
	],
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	platform: "node",
	minify: prod,
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
