// LaTeX viewer — Obsidian adapter over omni-viewer-core 0.11.
//
// The core owns structural parsing, editing, include resolution and rendering.
// This adapter supplies vault/file services plus statically bundled KaTeX and
// DOMPurify dependencies. The core self-loader is deliberately not used: its
// non-literal dynamic imports cannot be followed into Obsidian's single-file
// plugin bundle.

import * as fs from 'fs';
import * as path from 'path';
import createDOMPurify from 'dompurify';
import katex from 'katex';
import { normalizePath, Platform, TFile } from 'obsidian';
import type { FileSaveService } from 'omni-viewer-core/host';
import { resolveCatalogMessage } from 'omni-viewer-core/i18n';
import {
    mountLatexViewer,
    type DomPurify,
    type LatexViewerContext,
    type LatexViewerDeps,
    type MathRenderer
} from 'omni-viewer-core/viewers/latex';
import { openExternal, showSaveDialog } from '../platform';
import { getBundledAssetDataUri, getBundledTextAsset } from '../utils/bundledAssets';
import { saveBinaryBesideFile } from '../utils/vaultFiles';
import { RenderContext, ViewerDefinition } from '../viewerCore';

const KATEX_CSS_KEY = 'node_modules/katex/dist/katex.min.css';
const KATEX_FONT_ROOT = 'node_modules/katex/dist/fonts';
const MOBILE_LATEX_CSS = `
.omni-latex__toolbar{flex-wrap:wrap;gap:8px}
.omni-latex__source{font-size:max(16px,var(--font-ui-small))}
.omni-latex__preview,.omni-latex__source{overscroll-behavior:contain}
`;

function toArrayBuffer(data: Uint8Array): ArrayBuffer {
    return data.buffer.slice(data.byteOffset, data.byteOffset + data.byteLength) as ArrayBuffer;
}

/**
 * KaTeX's published CSS references woff2/woff/ttf files. The release is a
 * single main.js, so retain only woff2 and replace every URL with an embedded
 * data URI generated by the existing asset pipeline.
 */
function bundledKatexCss(): string {
    const source = getBundledTextAsset(KATEX_CSS_KEY);
    if (!source) throw new Error('Bundled KaTeX stylesheet is unavailable.');

    return source
        .replace(/,url\(fonts\/[^)]+\.(?:woff|ttf)\) format\("(?:woff|truetype)"\)/g, '')
        .replace(/url\(fonts\/([^)]+\.woff2)\)/g, (_match, fileName: string) => {
            const uri = getBundledAssetDataUri(`${KATEX_FONT_ROOT}/${fileName}`);
            if (!uri) throw new Error(`Bundled KaTeX font is unavailable: ${fileName}`);
            return `url(${uri})`;
        });
}

let katexCss: string | undefined;

const mathRenderer: MathRenderer = {
    renderToHtml: (source, displayMode, options) => katex.renderToString(source, {
        displayMode,
        throwOnError: false,
        errorColor: 'var(--omni-warning, #cca700)',
        output: 'htmlAndMathml',
        trust: false,
        ...(options?.macros ? { macros: options.macros } : {})
    })
};

// DOMPurify's default export is a window-bound instance in browsers and a
// factory in non-DOM runtimes. Calling it with the viewer window is the stable
// cross-runtime form used by the core's own self-loader.
const purifierFactory = createDOMPurify as unknown as (window: Window) => DomPurify;

const latexDeps: LatexViewerDeps = {
    math: mathRenderer,
    createDOMPurify: (window) => purifierFactory(window)
};

function createSaveService(ctx: RenderContext): FileSaveService {
    return {
        saveFile: async (name, data) => {
            if (Platform.isMobileApp) {
                await saveBinaryBesideFile(ctx.app, ctx.file, name, data);
                return;
            }
            const targetPath = await showSaveDialog(
                path.join(path.dirname(ctx.filePath), name),
                [{ name: 'LaTeX', extensions: ['tex', 'latex', 'ltx'] }]
            );
            if (!targetPath) return { status: 'cancelled' };
            await fs.promises.writeFile(targetPath, data);
            return { status: 'saved', fileName: path.basename(targetPath) };
        }
    };
}

function createHostContext(ctx: RenderContext): LatexViewerContext {
    const context: LatexViewerContext = {
        assets: { resolveAssetUrl: async (assetPath) => assetPath },
        i18n: { t: (key, args) => resolveCatalogMessage(key, args) },
        logger: {
            log: (level, message) => {
                const prefix = '[omni-viewer latex]';
                if (level === 'error') console.error(prefix, message);
                else if (level === 'warn') console.warn(prefix, message);
                else console.info(prefix, message);
            }
        },
        navigation: {
            openExternalUrl: async (url) => { openExternal(url); }
        },
        save: createSaveService(ctx),
        writeback: {
            write: async (data) => {
                ctx.host.markInternalWrite?.();
                await ctx.app.vault.modifyBinary(ctx.file, toArrayBuffer(data));
            }
        }
    };
    if (typeof navigator !== 'undefined' && navigator.clipboard?.writeText) {
        context.clipboard = { writeText: (text) => navigator.clipboard.writeText(text) };
    }
    return context;
}

function createIncludeResolver(ctx: RenderContext): (includePath: string) => Promise<string | null> {
    const root = ctx.file.parent?.path ?? '';
    const rootPrefix = root ? `${root}/` : '';
    return async (includePath) => {
        const targetPath = normalizePath(rootPrefix ? `${rootPrefix}${includePath}` : includePath);
        // Core rejects traversal before invoking us; keep the vault boundary
        // here too in case its normalization contract changes later.
        if (rootPrefix && !targetPath.startsWith(rootPrefix)) return null;
        const target = ctx.app.vault.getAbstractFileByPath(targetPath);
        if (!(target instanceof TFile)) return null;
        return ctx.app.vault.cachedRead(target);
    };
}

export const latexViewer: ViewerDefinition = {
    viewType: 'omni-viewer.latexViewer',
    displayName: 'LaTeX Viewer',
    extensions: ['tex', 'latex', 'ltx'],
    icon: 'sigma',
    errorContent: {
        title: 'Failed to load LaTeX file',
        message: 'Unable to parse or render the LaTeX file:',
        icon: 'TeX'
    },
    async render(ctx) {
        if (!ctx.host.provideDomContainer || !ctx.host.setCoreViewerHandle) {
            throw new Error('Host does not support direct DOM mounting');
        }

        const data = new Uint8Array(await ctx.app.vault.readBinary(ctx.file));
        const mathCss = katexCss ??= bundledKatexCss();
        const container = ctx.host.provideDomContainer();
        const handle = await mountLatexViewer(
            { fileName: ctx.fileName, data },
            container,
            createHostContext(ctx),
            {
                deps: latexDeps,
                resolveInclude: createIncludeResolver(ctx)
            }
        );

        // The core stylesheet is injected into its shadow root. KaTeX layout
        // rules and fonts must live in the same root because document-global CSS
        // does not cross that boundary.
        const root = container.shadowRoot;
        if (!root) {
            handle.dispose();
            throw new Error('LaTeX viewer style isolation could not be initialized.');
        }
        const style = document.createElement('style');
        style.dataset.omniKatex = 'true';
        style.textContent = mathCss + (Platform.isMobileApp ? MOBILE_LATEX_CSS : '');
        root.append(style);

        // Core 0.12 exposes the controller's dirty state on the mount handle,
        // so the host can guard refresh/share without depending on core DOM.
        ctx.host.setCoreViewerHandle(handle);
    }
};
