import fs from "fs";
import path from "path";

const rootDir = process.cwd();
const generatedDir = path.join(rootDir, "src", "generated");
const outputPath = path.join(generatedDir, "assets.ts");

const textRoots = ["templates"];
const binaryFiles = [
  "wasm/audio_engine.wasm",
  "templates/hwp/vendor/rhwp/rhwp_bg.wasm",
];

const extraTextFiles = [
  "wasm/audio_engine.js",
];

function normalizeKey(filePath) {
  return filePath.split(path.sep).join("/");
}

function walkFiles(dir) {
  if (!fs.existsSync(dir)) {
    return [];
  }

  const files = [];
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const entryPath = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      files.push(...walkFiles(entryPath));
    } else if (entry.isFile()) {
      files.push(entryPath);
    }
  }
  return files;
}

function textAssetEntries() {
  const files = [];
  for (const root of textRoots) {
    files.push(...walkFiles(path.join(rootDir, root)));
  }
  for (const rel of extraTextFiles) {
    const abs = path.join(rootDir, rel);
    if (fs.existsSync(abs)) {
      files.push(abs);
    }
  }

  return files
    .filter((file) => !binaryFiles.includes(normalizeKey(path.relative(rootDir, file))))
    .sort()
    .map((file) => {
      const rel = normalizeKey(path.relative(rootDir, file));
      return [rel, fs.readFileSync(file, "utf8")];
    });
}

function binaryAssetEntries() {
  return binaryFiles
    .filter((rel) => fs.existsSync(path.join(rootDir, rel)))
    .map((rel) => [rel, fs.readFileSync(path.join(rootDir, rel)).toString("base64")]);
}

function renderRecord(entries) {
  return entries
    .map(([key, value]) => `  ${JSON.stringify(key)}: ${JSON.stringify(value)},`)
    .join("\n");
}

fs.mkdirSync(generatedDir, { recursive: true });

const output = `// Generated by scripts/build-assets.mjs. Do not edit by hand.

export const BUNDLED_TEXT_ASSETS: Record<string, string> = {
${renderRecord(textAssetEntries())}
};

export const BUNDLED_BINARY_ASSETS_BASE64: Record<string, string> = {
${renderRecord(binaryAssetEntries())}
};
`;

fs.writeFileSync(outputPath, output);
console.log(`Generated ${path.relative(rootDir, outputPath)}`);
